Permit pydantic v2
permitio/fastapi_websocket_pubsub pull request #65
Opened 2023-09-03 18:43 UTC by ff137

2023-09-18 14:10 UTC, orweis commented
> These tests will fail until [permitio/fastapi_websocket_rpc#24](https://github.com/permitio/fastapi_websocket_rpc/pull/24) is merged and published, because this PR requires `fastapi_websocket_rpc~=0.1.25` (the version in aforementioned PR). Setting to draft until that's merged.

Of course :)

2023-09-19 14:28 UTC, roekatz requested changes
Same comments as in https://github.com/permitio/fastapi_websocket_rpc/pull/24.
Don't worry about the versions, I'll release those once we merge.

2023-09-20 10:01 UTC, roekatz approved these changes

2023-09-20 11:23 UTC, ff137 commented
@roekatz I notice there's a timeout error for one of the tests. I can't really infer from the logs what's going on there ...

2023-09-20 12:35 UTC, merged

2023-09-20 14:29 UTC, roekatz commented
@ff137 I'll fix it separately, I don't think it's related to your changes